version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: barista_db
      POSTGRES_USER: barista_user
      POSTGRES_PASSWORD: barista_pass
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DB_NAME=barista_db
      - DB_USER=barista_user
      - DB_PASSWORD=barista_pass
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
